// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Session struct {
	ID           int64     `json:"id"`
	SessionToken string    `json:"sessionToken"`
	UserID       int64     `json:"userId"`
	CreatedAt    time.Time `json:"createdAt"`
	ExpiresAt    time.Time `json:"expiresAt"`
	IsActive     int64     `json:"isActive"`
}

type User struct {
	ID             int64      `json:"id"`
	Username       string     `json:"username"`
	PasswordHash   string     `json:"passwordHash"`
	MfaEnabled     int64      `json:"mfaEnabled"`
	TotpSecret     *string    `json:"totpSecret"`
	FailedAttempts int64      `json:"failedAttempts"`
	LockedUntil    *time.Time `json:"lockedUntil"`
	CreatedAt      time.Time  `json:"createdAt"`
	LastLoginAt    *time.Time `json:"lastLoginAt"`
}
