// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (session_token, user_id, expires_at)
    VALUES (?, ?, datetime ('now', '+7 days'))
RETURNING
    id, session_token, user_id, created_at, expires_at, is_active
`

type CreateSessionParams struct {
	SessionToken string `json:"sessionToken"`
	UserID       int64  `json:"userId"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.SessionToken, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT
    id, session_token, user_id, created_at, expires_at, is_active
FROM
    sessions
WHERE
    session_token = ?
    AND is_active = 1
    AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetActiveSession(ctx context.Context, sessionToken string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getActiveSession, sessionToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}
