// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (session_token, user_id, expires_at)
    VALUES (lower(hex (randomblob (32))), ?, ?)
RETURNING
    session_token
`

type CreateSessionParams struct {
	UserID    int64     `json:"userId"`
	ExpiresAt time.Time `json:"expiresAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.ExpiresAt)
	var session_token string
	err := row.Scan(&session_token)
	return session_token, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE user_id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, userID)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT
    id, session_token, user_id, created_at, expires_at, is_active
FROM
    sessions
WHERE
    session_token = ?
    AND is_active = 1
    AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetActiveSession(ctx context.Context, sessionToken string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getActiveSession, sessionToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}
