// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash)
    VALUES (?, ?)
RETURNING
    id, username, password_hash, mfa_enabled, totp_secret, failed_attempts, locked_until, created_at, last_login_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.TotpSecret,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
    id, username, password_hash, mfa_enabled, totp_secret, failed_attempts, locked_until, created_at, last_login_at
FROM
    users
WHERE
    username = ?
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.MfaEnabled,
		&i.TotpSecret,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
